#!/bin/bash

# 1. FAIL-FAST: Exit immediately if any command returns a non-zero status
set -e

# 2. PRE-FLIGHT CHECKS
# Added GITHUB_ISSUE_NUMBER to the requirements
if [ -z "$TASK_ID" ] || [ -z "$DB_PATH" ] || [ -z "$GITHUB_TOKEN" ] || [ -z "$GITHUB_ISSUE_NUMBER" ]; then
    echo "❌ [Worker] Error: Missing required environment variables."
    exit 1
fi

echo "[Worker] Starting Task: $TASK_ID"

# 3. THE HEARTBEAT (Cross-platform compatible)
# We use $(($(date +%s) * 1000)) to support both Linux and macOS
(
  while true; do
    sleep 15
    sqlite3 "$DB_PATH" "UPDATE tasks SET lastHeartbeat = $(($(date +%s) * 1000)) WHERE id = '$TASK_ID';"
  done
) &
HEARTBEAT_PID=$!

# Ensure the heartbeat dies, and suppress the "Terminated" message
trap "kill $HEARTBEAT_PID 2>/dev/null || true" EXIT

# 4. GIT OPERATIONS
BRANCH_NAME="fix/beav-$TASK_ID"

echo "🌿 [Worker] Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

#AI LOGIC
echo "[Worker] Calling Node.js AI Specialist..."

npx ts-node ./src/fix_code.ts "./src/index.ts" "$ISSUE_BODY"

echo "[Worker] Files have been modified by the AI."

echo "// Fix applied by Beav at $(date)" >> fix_log.txt

echo "[Worker] Preparing commit..."
git add .

# SECURITY CHECK: Don't try to commit if nothing changed
if git diff --cached --quiet; then
    echo "⚠️ [Worker] Nothing to commit. Exiting."
    exit 1
fi

git commit -m "fix: automated resolution for issue #$GITHUB_ISSUE_NUMBER"

echo "⬆️ [Worker] Pushing to origin..."
git push origin "$BRANCH_NAME"

# 5. PR CREATION
echo "📝 [Worker] Creating Pull Request..."
pr_url=$(gh pr create \
    --title "Beav Fix for Issue #$GITHUB_ISSUE_NUMBER" \
    --body "Automated fix generated by Beav for task $TASK_ID." \
    --head "$BRANCH_NAME" \
    --base "main")

echo "✅ [Worker] PR Created: $pr_url"

exit 0